import React, { useEffect, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { CheckCircle2, RefreshCw, Fingerprint, Plus, Trash2, KeyRound, Download, Send, ShieldCheck } from 'lucide-react';
import type { User, SettingsData, TelegramStatus, Passkey, Chat, Notify, Action } from './types';
import type { RegistrationOptions } from './passkeys';
import { api, post, put, del, date, bytes, errorMessage } from './api';
import { createPasskey } from './passkeys';
import { Notice, Spinner, CopyField, Modal } from './components';

function Section({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="settings-card"><header><h3>{title}</h3>{description && <p>{description}</p>}</header>{children}</section>; }
export default function Settings({ user, notify, onLogout }: { user: User; notify: Notify; onLogout: () => void }) {
  const [settings, setSettings] = useState<SettingsData | null>(null), [telegram, setTelegram] = useState<TelegramStatus | null>(null), [busy, setBusy] = useState(false), [keys, setKeys] = useState<Record<string, string | number> | null>(null), [passkeys, setPasskeys] = useState<Passkey[]>([]);
  const [credentials, setCredentials] = useState({ api_id: '', api_hash: '' }), [value, setValue] = useState(''), [chat, setChat] = useState('me'), [chats, setChats] = useState<Chat[]>([]), [bot, setBot] = useState({ name: '', token: '' }), [password, setPassword] = useState({ old_password: '', password: '' }), [link, setLink] = useState('');
  const admin = user.role === 'admin';
  async function load() { const data = await api<SettingsData>('/api/settings'); setSettings(data); if (admin) { setTelegram(data.telegram ?? null); setChat(data.storage_chat ?? 'me'); setCredentials(c => ({ ...c, api_id: data.telegram_api_id ? String(data.telegram_api_id) : '' })); } setPasskeys(await api<Passkey[]>('/api/profile/passkeys')); }
  useEffect(() => { load().catch(e => notify(errorMessage(e), true)); }, []);
  useEffect(() => { if (!admin) return; let active = true; const timer = setInterval(() => api<TelegramStatus>('/api/settings/telegram').then(r => active && setTelegram(r)).catch(() => {}), 1800); return () => { active = false; clearInterval(timer); }; }, [admin]);
  const action: Action = async (fn, message) => { setBusy(true); try { await fn(); if (message) notify(message); await load(); } catch (e) { notify(errorMessage(e), true); } finally { setBusy(false); } }
  const main = telegram?.accounts?.find(a => a.key === 'main');
  const state = main?.state?.['@type'];
  const ready = state === 'authorizationStateReady';
  const stages: Record<string, [string, string]> = { authorizationStateWaitCode: ['code', 'Mã xác nhận Telegram'], authorizationStateWaitPassword: ['password', 'Mật khẩu xác minh hai bước'], authorizationStateWaitEmailAddress: ['email', 'Email xác minh'], authorizationStateWaitEmailCode: ['email_code', 'Mã xác nhận email'] };
  const stage = stages[state ?? ''];
  if (!settings) return <div className="loading"><Spinner/>Đang tải cài đặt…</div>;
  const readyBotCount = telegram?.accounts?.filter(a => a.bot && a.state?.['@type'] === 'authorizationStateReady' && !a.cooldown_seconds).length || 0;
  return <div className="settings-grid">
    {admin && <>
      <Section title="Kết nối Telegram" description="Đăng nhập bằng QR để dùng Telegram làm nơi lưu trữ.">
        {telegram?.error && <Notice error>{telegram.error}</Notice>}
        {ready ? <div className="connection-ready"><CheckCircle2/><div><strong>Đã kết nối {main?.me?.first_name}</strong><p>ID {main?.me?.id}</p></div><button className="button danger subtle" disabled={busy} onClick={() => { if (confirm('Đăng xuất Telegram? Tác vụ lưu trữ sẽ dừng cho đến khi kết nối lại.')) action(() => post('/api/settings/telegram/auth', { action: 'logout' })); }}>Đăng xuất</button></div> : <>
          <details open={!settings.telegram_api_id}><summary>Telegram API credentials</summary><form className="form-stack flex flex-col gap-4" onSubmit={e => { e.preventDefault(); action(() => post('/api/settings/telegram', { api_id: Number(credentials.api_id), api_hash: credentials.api_hash }), 'Đã lưu cấu hình Telegram'); }}><p className="muted">Lấy API ID và API hash tại <a href="https://my.telegram.org/apps" target="_blank" rel="noreferrer">my.telegram.org/apps</a>.</p><label>API ID<input required type="number" value={credentials.api_id} onChange={e => setCredentials({ ...credentials, api_id: e.target.value })}/></label><label>API hash<input type="password" placeholder={settings.telegram_api_id ? 'Để trống để giữ nguyên' : '32 ký tự'} value={credentials.api_hash} onChange={e => setCredentials({ ...credentials, api_hash: e.target.value })}/></label><button className="button" disabled={busy}>Lưu và khởi tạo</button></form></details>
          {main?.state?.error && <Notice error>{main.state.error}</Notice>}
          {state === 'authorizationStateWaitOtherDeviceConfirmation' && main?.state.link ? <div className="qr-panel"><div className="qr-box"><QRCodeSVG value={main?.state.link} size={208} level="M" marginSize={3}/></div><strong>Quét bằng ứng dụng Telegram</strong><p>Telegram → Cài đặt → Thiết bị → Liên kết thiết bị máy tính.</p><small>Mã tự cập nhật khi Telegram cấp mã mới.</small></div> : null}
          {stage ? <form className="form-stack flex flex-col gap-4" onSubmit={e => { e.preventDefault(); action(async () => { await post('/api/settings/telegram/auth', { action: stage[0], value }); setValue(''); }); }}><label>{stage[1]}<input required type={stage[0] === 'password' ? 'password' : 'text'} value={value} onChange={e => setValue(e.target.value)} autoComplete="off"/></label><button className="button primary" disabled={busy}>Xác nhận</button></form> : <div className="form-stack flex flex-col gap-4"><button className="button primary" disabled={busy || !telegram?.available || !settings.telegram_api_id} onClick={() => action(() => post('/api/settings/telegram/auth', { action: 'qr' }))}><RefreshCw size={16}/>Hiện mã QR đăng nhập</button><details><summary>Dùng số điện thoại</summary><form onSubmit={e => { e.preventDefault(); action(() => post('/api/settings/telegram/auth', { action: 'phone', value })); }} className="inline-form"><input placeholder="+84…" value={value} onChange={e => setValue(e.target.value)} required/><button className="button" disabled={busy}>Tiếp tục</button></form></details></div>}
          <small className="muted">Trạng thái: {state || 'Chưa khởi tạo'}</small>
        </>}
      </Section>
      <Section title="Nơi lưu dữ liệu" description="Chọn Saved Messages hoặc một nhóm/kênh bạn có quyền gửi tài liệu."><form className="form-stack flex flex-col gap-4" onSubmit={e => { e.preventDefault(); action(() => put('/api/settings', { storage_chat: chat }), 'Đã đổi nơi lưu mặc định'); }}><label>Chat lưu trữ<input list="telegram-chats" value={chat} onChange={e => setChat(e.target.value)} placeholder="me, @username hoặc chat ID"/><datalist id="telegram-chats"><option value="me">Saved Messages</option>{chats.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</datalist></label><div className="button-row flex flex-wrap items-center gap-2.5"><button className="button primary" disabled={busy}>Lưu</button><button type="button" className="button" disabled={!ready || busy} onClick={() => action(async () => setChats(await api<Chat[]>('/api/settings/telegram/chats')))}>Lấy danh sách chat</button></div></form><p className="muted">File đã lưu tiếp tục dùng chat cũ. Kích thước mỗi phần: {bytes(settings.part_size)}.</p></Section>
      <Section title="Pool upload Telegram" description="Phân phối các phần file giữa tài khoản chính và bot đã kết nối.">
        <dl className="pool-metrics">
          <div><dt>Bot sẵn sàng</dt><dd>{readyBotCount}<span> / {settings.bots?.length || 0}</span></dd></div>
          <div><dt>Tác vụ đồng thời</dt><dd>{settings.max_parallel_uploads ?? 2}</dd></div>
          <div><dt>Nơi lưu đã chọn</dt><dd className="pool-destination">{settings.storage_chat === 'me' ? 'Saved Messages' : settings.storage_chat}</dd></div>
        </dl>
        {settings.storage_chat === 'me' && <Notice>Saved Messages chỉ dùng tài khoản chính. Để bot tham gia upload, chọn một nhóm hoặc kênh lưu trữ mà tài khoản chính và các bot đều có quyền truy cập.</Notice>}
        <p className="muted">Nhiều bot có thể giúp tăng tổng thông lượng khi có nhiều file chạy đồng thời. Mỗi file vẫn gửi từng phần tuần tự; tốc độ phụ thuộc mạng và giới hạn Telegram.</p>
        <details><summary>Cách kết nối bot để upload</summary><ol className="setup-steps"><li>Tạo bot qua @BotFather và lấy token.</li><li>Thêm bot cùng tài khoản chính vào nhóm/kênh lưu trữ. Cho bot quyền gửi tài liệu; với kênh, cần quyền đăng bài.</li><li>Lưu chat ID hoặc @username tại mục Nơi lưu dữ liệu.</li><li>Thêm token bên dưới và đợi bot báo sẵn sàng. Giới hạn tác vụ đồng thời được cấu hình trên máy chủ.</li></ol></details>
        {settings.bots?.map(b => { const account = telegram?.accounts.find(a => a.key === b.id); return <div className="item-row" key={b.id}><div><strong>{b.name}</strong><small>{account?.state?.['@type'] === 'authorizationStateReady' ? 'Đã đăng nhập' : account?.state?.['@type'] || 'Chưa kết nối'}</small>{(account?.cooldown_seconds ?? 0) > 0 && <small>Chờ {account?.cooldown_seconds}s trước lượt tiếp theo</small>}{account?.state?.error && <small className="error-text">{account?.state.error}</small>}</div><button className="icon-button danger" title="Gỡ bot" onClick={() => { if (confirm(`Gỡ ${b.name}?`)) action(() => del(`/api/settings/bots/${b.id}`)); }}><Trash2 size={17}/></button></div>; })}<form className="form-stack flex flex-col gap-4" onSubmit={e => { e.preventDefault(); action(async () => { await post('/api/settings/bots', bot); setBot({ name: '', token: '' }); }, 'Đã thêm bot'); }}><label>Tên bot<input required value={bot.name} onChange={e => setBot({ ...bot, name: e.target.value })}/></label><label>Bot token<input required type="password" value={bot.token} onChange={e => setBot({ ...bot, token: e.target.value })}/></label><button className="button" disabled={busy}><Plus size={16}/>Thêm bot</button></form></Section>
      <Section title="Sao lưu metadata" description="Bản ZIP gồm SQLite và thumbnail. Giữ bản sao master.key và thư mục phiên TDLib riêng."><label className="check-label"><input type="checkbox" checked={settings.backup_enabled || false} disabled={busy} onChange={e => action(() => put('/api/settings', { backup_enabled: e.target.checked }))}/>Gửi bản sao lưu lên Telegram mỗi ngày</label><p className="muted">Lần gửi gần nhất: {date(Number(settings.last_backup))}</p><div className="button-row flex flex-wrap items-center gap-2.5"><a className="button" href="/api/admin/backup"><Download size={16}/>Tải ZIP</a><button className="button" disabled={busy || !ready} onClick={() => action(() => post('/api/admin/backup/telegram'), 'Đã gửi bản sao lưu')}><Send size={16}/>Gửi Telegram</button></div><details><summary>Khôi phục dữ liệu</summary><p>Thay thế metadata hiện tại bằng bản sao lưu Rust. Server sẽ tự thoát; cần cơ chế khởi động lại. Không dùng database của bản Go.</p><label className="button danger">Chọn ZIP khôi phục<input hidden type="file" accept=".zip" onChange={e => { const file = e.target.files?.[0]; if (file && confirm('Thay thế toàn bộ metadata bằng bản sao lưu này?')) action(() => api('/api/admin/restore', { method: 'POST', body: file, headers: { 'Content-Type': 'application/zip', 'X-Confirm-Restore': 'REPLACE' } }), 'Đã nhận bản khôi phục. Đợi server khởi động lại.'); e.target.value = ''; }}/></label></details></Section>
    </>}
    <Section title="Passkey" description="Dùng vân tay, Face ID hoặc khóa bảo mật để đăng nhập web.">{passkeys.map(p => <div className="item-row" key={p.id}><div><strong>{p.name}</strong><small>{date(p.created_at)}</small></div><button className="icon-button danger" title="Xóa passkey" onClick={() => action(() => del(`/api/profile/passkeys/${p.id}`))}><Trash2 size={17}/></button></div>)}<button className="button" disabled={busy} onClick={() => { const name = prompt('Tên passkey', 'Thiết bị của tôi'); if (name) action(async () => { const options = await post<RegistrationOptions>('/api/profile/passkeys/begin'); const credential = await createPasskey(options); await post('/api/profile/passkeys/finish', { name, credential }); }, 'Đã thêm passkey'); }}><Fingerprint size={18}/>Thêm passkey</button></Section>
    <Section title="API, WebDAV & S3" description="Khóa mới thay thế khóa cũ. Hãy sao chép và lưu trước khi đóng."><p className="muted">WebDAV: <code>{settings.public_url}/webdav/</code></p><div className="button-row flex flex-wrap items-center gap-2.5"><button className="button" onClick={() => action(async () => setKeys(await post<Record<string, string | number>>('/api/profile/keys', { kind: 'api' })))}><KeyRound size={16}/>Tạo API key</button><button className="button" onClick={() => action(async () => setKeys(await post<Record<string, string | number>>('/api/profile/keys', { kind: 's3' })))}>Tạo khóa S3</button></div><p className="muted">WebDAV dùng tên tài khoản + mật khẩu hoặc API key. S3 dùng path-style, bucket itclub-cloud.</p><div className="button-row flex flex-wrap items-center gap-2.5"><button className="button subtle danger" onClick={() => { if (confirm('Thu hồi API key?')) action(() => post<Record<string, string | number>>('/api/profile/keys', { kind: 'revoke_api' })); }}>Thu hồi API key</button><button className="button subtle danger" onClick={() => { if (confirm('Thu hồi khóa S3?')) action(() => post<Record<string, string | number>>('/api/profile/keys', { kind: 'revoke_s3' })); }}>Thu hồi S3</button></div></Section>
    <Section title="Gửi file qua bot" description="Liên kết tài khoản Telegram cá nhân để file gửi riêng cho bot được đưa vào thư viện."><div className="button-row flex flex-wrap items-center gap-2.5"><button className="button" onClick={() => action(async () => setLink((await post<{ command: string }>('/api/profile/telegram/link')).command))}>Tạo mã liên kết</button><button className="button subtle danger" onClick={() => action(async () => { await del('/api/profile/telegram/link'); setLink(''); }, 'Đã hủy liên kết')}>Hủy liên kết</button></div>{link && <><p>Gửi lệnh này trong chat riêng với một bot đã cấu hình. Mã hết hạn sau 10 phút.</p><CopyField value={link}/></>}</Section>
    <Section title="Đổi mật khẩu" description="Sau khi đổi, các phiên đăng nhập web sẽ kết thúc."><form className="form-stack flex flex-col gap-4" onSubmit={e => { e.preventDefault(); action(async () => { await post('/api/profile/password', password); onLogout(); }); }}><label>Mật khẩu hiện tại<input required type="password" autoComplete="current-password" value={password.old_password} onChange={e => setPassword({ ...password, old_password: e.target.value })}/></label><label>Mật khẩu mới<input required type="password" minLength={10} autoComplete="new-password" value={password.password} onChange={e => setPassword({ ...password, password: e.target.value })}/></label><button className="button" disabled={busy}><ShieldCheck size={16}/>Đổi mật khẩu</button></form></Section>
    {keys && <Modal title="Khóa truy cập của bạn" subtitle="Chỉ hiển thị tại lần tạo này. Đừng chia sẻ khóa với người khác." onClose={() => setKeys(null)}>{Object.entries(keys).map(([name, value]) => <label key={name}>{name}<CopyField value={String(value)}/></label>)}</Modal>}
  </div>;
}
export function Users({ notify }: { notify: Notify }) {
  const [users, setUsers] = useState<User[]>([]), [form, setForm] = useState({ username: '', password: '', quota: '0' }), [busy, setBusy] = useState(false);
  const load = () => api<User[]>('/api/admin/users').then(setUsers);
  useEffect(() => { load().catch(e => notify(errorMessage(e), true)); }, []);
  const action: Action = async (fn) => { setBusy(true); try { await fn(); await load(); } catch (e) { notify(errorMessage(e), true); } finally { setBusy(false); } }
  return <div className="settings-grid"><Section title="Thành viên" description="Mỗi tài khoản có thư viện riêng.">{users.map(u => <div className="item-row" key={u.id}><div><strong>{u.username}</strong><small>{u.role} · {u.disabled ? 'Đã khóa' : 'Hoạt động'} · {u.quota_bytes ? bytes(u.quota_bytes) : 'Không giới hạn quota'}</small></div>{u.role !== 'admin' && <div className="button-row flex flex-wrap items-center gap-2.5"><button className="button small" disabled={busy} onClick={() => action(() => put(`/api/admin/users/${u.id}`, { disabled: !u.disabled }))}>{u.disabled ? 'Mở' : 'Khóa'}</button><button className="button small" onClick={() => { const quota = prompt('Quota GiB, 0 = không giới hạn', String(u.quota_bytes / 1073741824)); if (quota !== null && Number(quota) >= 0) action(() => put(`/api/admin/users/${u.id}`, { quota_bytes: Math.round(Number(quota) * 1073741824) })); }}>Quota</button><button className="button small" onClick={() => { const password = prompt('Mật khẩu mới (ít nhất 10 ký tự)'); if (password) action(() => put(`/api/admin/users/${u.id}`, { password })); }}>Mật khẩu</button><button className="icon-button danger" title="Xóa thành viên" onClick={() => { if (confirm(`Xóa vĩnh viễn tài khoản ${u.username} và dữ liệu của họ?`)) action(() => del(`/api/admin/users/${u.id}`)); }}><Trash2 size={17}/></button></div>}</div>)}</Section><Section title="Thêm thành viên"><form className="form-stack flex flex-col gap-4" onSubmit={e => { e.preventDefault(); action(async () => { await post('/api/admin/users', { username: form.username, password: form.password, quota_bytes: Math.round(Number(form.quota) * 1073741824) }); setForm({ username: '', password: '', quota: '0' }); }); }}><label>Tên tài khoản<input required value={form.username} onChange={e => setForm({ ...form, username: e.target.value })}/></label><label>Mật khẩu<input required type="password" minLength={10} value={form.password} onChange={e => setForm({ ...form, password: e.target.value })}/></label><label>Quota GiB (0 = không giới hạn)<input type="number" min="0" value={form.quota} onChange={e => setForm({ ...form, quota: e.target.value })}/></label><button disabled={busy} className="button primary"><Plus size={16}/>Thêm thành viên</button></form></Section></div>;
}
